# Generated by Django 5.1 on 2024-09-14 09:40

import apps.companies.validators
import apps.users.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=13, validators=[apps.users.validators.validate_phone_number])),
                ('delivery', models.BooleanField(default=False)),
                ('region', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('_id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/%Y/%m/%d')),
                ('video', models.FileField(blank=True, null=True, upload_to='companies/videos/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4']), apps.companies.validators.validate_company_video_size])),
                ('banner', models.ImageField(blank=True, null=True, upload_to='companies/banners/%Y/%m/%d')),
                ('name', models.CharField(max_length=150)),
                ('username', models.SlugField(max_length=150, unique=True)),
                ('contact_number', models.CharField(max_length=13, validators=[apps.users.validators.validate_phone_number])),
                ('slogan', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1255)),
                ('delivery', models.BooleanField(default=False)),
                ('followers', models.CharField(default='0', max_length=40)),
                ('likes', models.CharField(default='0', max_length=50)),
                ('comments', models.CharField(default='0', max_length=50)),
                ('views', models.CharField(default='0', max_length=50)),
                ('web_site', models.URLField()),
                ('region', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('balance', models.DecimalField(decimal_places=1, default=0, max_digits=30)),
                ('total_rating', models.FloatField(blank=True, default=0, max_length=5, null=True)),
                ('rating5', models.PositiveSmallIntegerField(default=0)),
                ('rating4', models.PositiveSmallIntegerField(default=0)),
                ('rating3', models.PositiveSmallIntegerField(default=0)),
                ('rating2', models.PositiveSmallIntegerField(default=0)),
                ('rating1', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, to='categories.category')),
            ],
        ),
    ]
